pipeline:
  test:
    image: node:8
    commands:
    - npm install
    - npm test
  docker:
    image: plugins/docker
    registry: quay.io
    repo: natlibfi/melinda-transliteration-ui
    auto_tag: false
    secrets: [docker_username, docker_password]
